name: Python CI

on:
  push:
  #   branches: [main, develop]
  # pull_request:
  #   branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.13 # Adjust to your Python version

      - name: Install dependencies
        run: uv sync

      # - name: Run ruff linter
      #   run: uv run ruff check --fix --unsafe-fixes .
      #
      # - name: Run ruff formatter check
      #   run: uv run ruff format --check .

      - name: Run unit tests with pytest
        run: uv run pytest tests/unit/

      - name: Run endpoint tests with pytest
        run: uv run pytest tests/endpoint/

      - name: Run BDD FastAPI tests with pytest
        run: uv run pytest tests/bdd/*fastapi.py

      - name: Install Playwright browsers
        run: |
          uv add pytest-playwright
          python -m playwright install --with-deps

      - name: Run BDD browser tests with pytest
        run: uv run pytest tests/bdd/*browser.py
